'use client';

import { motion } from 'framer-motion';
import { DailyForecast } from '@/lib/weather';

interface CalendarExportProps {
  forecast: DailyForecast[];
  cityName: string;
}

export default function CalendarExport({ forecast, cityName }: CalendarExportProps) {
  
  const generateICS = () => {
    const events = forecast.slice(0, 7).map((day, idx) => {
      const date = new Date(day.dt * 1000);
      const dateStr = date.toISOString().split('T')[0].replace(/-/g, '');
      
      const event = [
        'BEGIN:VEVENT',
        `DTSTART;VALUE=DATE:${dateStr}`,
        `DTEND;VALUE=DATE:${dateStr}`,
        `SUMMARY:${cityName} Weather: ${day.description} ${Math.round(day.temp_max)}°/${Math.round(day.temp_min)}°`,
        `DESCRIPTION:High: ${Math.round(day.temp_max)}°F\\nLow: ${Math.round(day.temp_min)}°F\\nConditions: ${day.description}\\nHumidity: ${day.humidity}%\\nWind: ${Math.round(day.wind_speed)} mph${day.pop ? `\\nRain: ${Math.round(day.pop * 100)}%` : ''}`,
        `LOCATION:${cityName}, WA`,
        `UID:weather-${cityName}-${dateStr}@waweather.app`,
        'STATUS:CONFIRMED',
        'TRANSP:TRANSPARENT',
        'END:VEVENT'
      ].join('\r\n');
      
      return event;
    });
    
    const calendar = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//Washington Weather Hub//Weather Forecast//EN',
      'CALSCALE:GREGORIAN',
      'METHOD:PUBLISH',
      'X-WR-CALNAME:Weather Forecast - ' + cityName,
      'X-WR-TIMEZONE:America/Los_Angeles',
      ...events,
      'END:VCALENDAR'
    ].join('\r\n');
    
    return calendar;
  };

  const downloadICS = () => {
    const icsContent = generateICS();
    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `weather-forecast-${cityName.toLowerCase().replace(/\s+/g, '-')}.ics`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const addToGoogleCalendar = () => {
    const firstDay = forecast[0];
    const date = new Date(firstDay.dt * 1000);
    const dateStr = date.toISOString().split('T')[0].replace(/-/g, '');
    
    const title = encodeURIComponent(`${cityName} Weather: ${firstDay.description} ${Math.round(firstDay.temp_max)}°/${Math.round(firstDay.temp_min)}°`);
    const details = encodeURIComponent(`High: ${Math.round(firstDay.temp_max)}°F\nLow: ${Math.round(firstDay.temp_min)}°F\nConditions: ${firstDay.description}\nHumidity: ${firstDay.humidity}%\nWind: ${Math.round(firstDay.wind_speed)} mph${firstDay.pop ? `\nRain: ${Math.round(firstDay.pop * 100)}%` : ''}`);
    const location = encodeURIComponent(`${cityName}, WA`);
    
    const url = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&details=${details}&location=${location}&dates=${dateStr}/${dateStr}&allday=true`;
    
    window.open(url, '_blank');
  };

  const shareViaEmail = () => {
    const forecastText = forecast.slice(0, 7).map((day, idx) => {
      const date = new Date(day.dt * 1000);
      const dateStr = date.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
      return `${dateStr}: ${day.description} - High: ${Math.round(day.temp_max)}°F, Low: ${Math.round(day.temp_min)}°F`;
    }).join('\n');
    
    const subject = encodeURIComponent(`7-Day Weather Forecast for ${cityName}`);
    const body = encodeURIComponent(`Here's the upcoming weather forecast for ${cityName}, WA:\n\n${forecastText}\n\nGenerated by Washington Weather Hub\nhttps://waweather.netlify.app`);
    
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.9 }}
      className="w-full max-w-4xl mx-auto"
    >
      <div className="bg-gradient-to-br from-green-500/10 to-emerald-500/10 backdrop-blur-sm rounded-3xl border border-white/20 p-6 shadow-xl">
        <h2 className="text-3xl font-bold mb-2">📅 Calendar Integration</h2>
        <p className="text-sm text-white/70 mb-6">Export weather forecasts to your calendar</p>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {/* Download .ics File */}
          <button
            onClick={downloadICS}
            className="bg-gradient-to-br from-blue-500/20 to-indigo-500/20 hover:from-blue-500/30 hover:to-indigo-500/30 backdrop-blur-sm rounded-xl border border-white/30 p-6 transition-all text-left group"
          >
            <div className="text-4xl mb-3 group-hover:scale-110 transition-transform">📥</div>
            <h3 className="font-bold text-lg mb-2">Download .ics File</h3>
            <p className="text-sm text-white/70 mb-3">
              Import into Apple Calendar, Outlook, or any calendar app
            </p>
            <div className="text-xs bg-black/20 rounded-lg p-2">
              ✅ Works with most calendar apps<br />
              ✅ 7-day forecast included<br />
              ✅ Offline access
            </div>
          </button>

          {/* Google Calendar */}
          <button
            onClick={addToGoogleCalendar}
            className="bg-gradient-to-br from-red-500/20 to-orange-500/20 hover:from-red-500/30 hover:to-orange-500/30 backdrop-blur-sm rounded-xl border border-white/30 p-6 transition-all text-left group"
          >
            <div className="text-4xl mb-3 group-hover:scale-110 transition-transform">📆</div>
            <h3 className="font-bold text-lg mb-2">Add to Google Calendar</h3>
            <p className="text-sm text-white/70 mb-3">
              Quick add to your Google Calendar
            </p>
            <div className="text-xs bg-black/20 rounded-lg p-2">
              ✅ One-click integration<br />
              ✅ Syncs across devices<br />
              ✅ Auto-updates (manual re-add for changes)
            </div>
          </button>

          {/* Share via Email */}
          <button
            onClick={shareViaEmail}
            className="bg-gradient-to-br from-purple-500/20 to-pink-500/20 hover:from-purple-500/30 hover:to-pink-500/30 backdrop-blur-sm rounded-xl border border-white/30 p-6 transition-all text-left group"
          >
            <div className="text-4xl mb-3 group-hover:scale-110 transition-transform">📧</div>
            <h3 className="font-bold text-lg mb-2">Share via Email</h3>
            <p className="text-sm text-white/70 mb-3">
              Email the forecast to yourself or others
            </p>
            <div className="text-xs bg-black/20 rounded-lg p-2">
              ✅ Text format (no attachments)<br />
              ✅ Easy to forward<br />
              ✅ Includes 7-day outlook
            </div>
          </button>
        </div>

        {/* Preview */}
        <div className="mt-6 p-4 bg-black/20 rounded-xl">
          <h3 className="font-semibold mb-3">📋 Forecast Preview (7 days)</h3>
          <div className="space-y-2 text-sm max-h-48 overflow-y-auto">
            {forecast.slice(0, 7).map((day, idx) => {
              const date = new Date(day.dt * 1000);
              const dateStr = date.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
              return (
                <div key={idx} className="flex items-center justify-between bg-white/5 rounded-lg p-2">
                  <div className="flex items-center gap-3">
                    <span className="w-24 font-medium">{dateStr}</span>
                    <img 
                      src={`http://openweathermap.org/img/wn/${day.icon}.png`}
                      alt={day.description}
                      className="w-8 h-8"
                    />
                    <span className="capitalize text-white/70">{day.description}</span>
                  </div>
                  <div className="flex items-center gap-4">
                    <span className="font-medium">
                      {Math.round(day.temp_max)}° / {Math.round(day.temp_min)}°
                    </span>
                    {day.pop && day.pop > 0.3 && (
                      <span className="text-blue-400 text-xs">💧 {Math.round(day.pop * 100)}%</span>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Tips */}
        <div className="mt-6 p-4 bg-blue-500/10 rounded-xl border border-blue-500/20">
          <p className="text-sm">
            <strong>💡 Pro Tip:</strong> Download the .ics file to import the entire 7-day forecast into your calendar at once. 
            Perfect for planning outdoor events, trips, or weekly activities!
          </p>
        </div>
      </div>
    </motion.div>
  );
}
